services:
  tomee:
    image: tomee:jre17-webprofile
    container_name: tomee_nasaWeb
    ports:
      - "8080:8080"
    volumes:
      - ./target:/usr/local/tomee/webapps
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db_nasaWeb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nasa
      MYSQL_USER: pere
      MYSQL_PASSWORD: peredev
    ports:
      - "3306:3306"
    volumes:
      - db_data_nasa:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_nasaWeb
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data_nasa: